import type { Metadata } from "next";
import { Space_Grotesk, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import MobileBottomNav from "@/components/layout/MobileBottomNav";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space", // CSS'deki var(--font-space) ile eşleşir
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope", // CSS'deki var(--font-manrope) ile eşleşir
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="flex flex-col justify-between min-h-full">
        <Header />
        <main className="px-outer">
          {children}
        </main>
        <Footer />
        <MobileBottomNav />
      </body>
    </html>
  );
}
